ArcadeData/arcadedb-docs

src/main/asciidoc/sql/SQL-Projections.md
=> correct << to [

src/main/asciidoc/studio/chapter.adoc
=> readability tweak

src/main/asciidoc/sql/SQL-Drop-Type.md
IF EXISTS is a powerful option in scripted manipulation of the database
=> IF EXISTS works for drop type

src/main/asciidoc/concepts/inheritance.adoc
=> Rename Orientdb to ArcadeDB

src/main/asciidoc/api/http.adoc, src/main/asciidoc/api/java-schema.adoc, src/main/asciidoc/sql/SQL-Create-Index.adoc, src/main/asciidoc/sql/SQL-Functions.adoc, src/main/asciidoc/sql/SQL-Introduction.adoc, src/main/asciidoc/sql/SQL-Methods.adoc, src/main/asciidoc/sql/chapter.adoc
Section 8 (SQL):
* fixed some internal links
* fixed method overview table
* minor mini fixes
=> Sec. 8: Table and link fixes.

src/main/asciidoc/sql/SQL-Functions.adoc, src/main/asciidoc/sql/SQL-Methods.adoc, src/main/asciidoc/sql/SQL-Select.adoc, src/main/asciidoc/sql/chapter.adoc
* Fix function table layout
* Fix some links
* Slightly rephrase `normalize()` and `toJSON()` descriptions
=> Sec 8 (SQL) Fixes

src/main/asciidoc/api/chapter.adoc, src/main/asciidoc/api/postgres.adoc, src/main/asciidoc/appendix/sql-syntax.adoc, src/main/asciidoc/concepts/basics.adoc, src/main/asciidoc/introduction/run.adoc, src/main/asciidoc/sql/SQL-Create-Property.adoc, src/main/asciidoc/sql/SQL-Functions.adoc, src/main/asciidoc/sql/SQL-Select.adoc, src/main/asciidoc/sql/chapter.adoc, src/main/asciidoc/studio/database.adoc, src/main/asciidoc/tools/upgrade.adoc
* Typo fixes
* Formatting fixes
* Added CREATE PROPERTY examples
=> Various Fixes

src/main/asciidoc/comparison/orientdb.adoc, src/main/asciidoc/server/server.adoc, src/main/asciidoc/tools/importer.adoc
* Added comment on ArcadeDB compared to OrientDB SQL dialects
* Added mini section on ARCADEDB_HOME environment variable previously not mentioned in the docs
* Added keyword to importer section
=> small content additions

src/main/asciidoc/appendix/datatypes.adoc, src/main/asciidoc/concepts/transactions.adoc, src/main/asciidoc/sql/SQL-Alter-Property.adoc, src/main/asciidoc/sql/SQL-Batch.adoc, src/main/asciidoc/sql/SQL-Functions.adoc, src/main/asciidoc/studio/main.adoc
* Sec. 5: Add SQL Script language option
* Sec. 8: Fix Transactions link, fix edit links, fix format function signature
* Sec. 11: Fix exponents in data type table
This should fix the last broken links :smile:
=> Minor fixes

src/main/asciidoc/api/http.adoc, src/main/asciidoc/appendix/settings.adoc, src/main/asciidoc/server/docker.adoc
* Sec. 4: Remove apparent empty line from docker example 
* Sec. 7: align password in get-server HTTP API example
* Sec. 11: add example for settings via environment variable
=> Small changes in examples

src/main/asciidoc/introduction/multimodel.adoc, src/main/asciidoc/tools/console.adoc
* Sec 2: Fix typos
* Sec 6: Add `drop database` console command and `<path>` arguments to commands
=> Two small fixes

src/main/asciidoc/api/http.adoc, src/main/asciidoc/appendix/sql-syntax.adoc, src/main/asciidoc/sql/SQL-Insert.adoc, src/main/asciidoc/sql/SQL-Where.adoc
* Fix typos in Section 7.4 (HTTP API)
* Fix typos in Section 8 (SQL)
* Add short description of new end-of-line comments
=> Add end-of-line comments and fix minor typos

src/main/asciidoc/appendix/managing-dates.adoc, src/main/asciidoc/tools/console.adoc, src/main/asciidoc/tools/importer.adoc, src/main/asciidoc/tools/restore.adoc
* I reworked and extended some parts of Section 6.1
* Some minor fixes in related sections.
=> Improve Console Section

src/main/asciidoc/sql/SQL-Functions.adoc
* Rephrased set(), list(), map() function!
* Remove merge functionality description from map() function as it does not work!
* Added link to distance() function
* Consistent dividers between functions
* Consistent syntax block
* Consistent SQL capitalization
* Changed examples that still used universal base clases
* Fixed typo
=> Refactor SQL function reference

src/main/asciidoc/api/http.adoc, src/main/asciidoc/sql/SQL-Functions.adoc
* Add docu for `exists` endpoint
* Fix HTML entity error by using unicode entity code in SQL functions
=> Add docu for exists endpoint

src/main/asciidoc/api/http.adoc
* Remove double quotes from boolean result
* Fix typo
=> Update `exists` endpoint example

src/main/asciidoc/appendix/chapter.adoc, src/main/asciidoc/appendix/requirements.adoc, src/main/asciidoc/sql/SQL-Projections.adoc, src/main/asciidoc/sql/SQL-Where.adoc, src/main/asciidoc/sql/chapter.adoc
* Resort SQL "Functions" table
* Fixed "Variables" table
* Fixed "Query Results" table
* Add "Requirements" section to Appendix
* Could you add an estimate for RAM requirements for the `high-performance` profile?
* Could you add more compatible JREs?
=> Table fixes and Requirements section

src/main/asciidoc/api/cypher.adoc, src/main/asciidoc/appendix/sql-syntax.adoc, src/main/asciidoc/sql/SQL-Where.adoc
* Add docu of null-safe equals operator to Filtering and Appendix
* Add mini tutorial on Cypher to Cypher Section
=> Null-safe equals docu and Cypher link

src/main/asciidoc/tools/console.adoc
These changes update the help block in the Console Section to match the  changes proposed in my latest PR. Particularly, this shouls only be merged if the console comment-command is merged in to main.
=> Update console help to match latest changes

src/main/asciidoc/security/users.adoc, src/main/asciidoc/server/server.adoc, src/main/asciidoc/sql/SQL-Batch.adoc, src/main/asciidoc/version.adoc
* Update version to 22.12.1.
* Fix list in SQL-Batch Section.
* Comment `console.X` commands in SQL-Batch Section out. 
* Add a small Logging Subsection to Server Section.
* Add a link to Console Section in Security - Users Section.
=> Minor updates

src/main/asciidoc/server/kubernetes.adoc
- added kubernetes config reference in the docs. It was confusing for me and couldn't find it myself without external help 
ref: https://github.com/ArcadeData/arcadedb/issues/699
=> [kubernetes] added ref for the config

src/main/asciidoc/tools/console.adoc
* Added `list databases` command to help block in Console section
* Added note on comment "command" in Console section
* Updated version of console help block
=> Add list command and note on comment

src/main/asciidoc/api/http.adoc, src/main/asciidoc/security/users.adoc, src/main/asciidoc/server/ha.adoc
* Update commands in `server` (POST) endpoint in Section 7.4
* Update create user reference in Section 9
* Add note on cluster databases in Section 4.4
=> HTTP API and minor updates

src/main/asciidoc/api/http.adoc, src/main/asciidoc/sql/SQL-Create-Bucket.adoc
* Deprecates open endpoint and updates server command in Section 7.4
* Remove comment on `ADDBUCKET` which I think is outdated or a leftover in Section 8.4
=> Open endpoint and addbucket

src/main/asciidoc/api/java-ref-database.adoc, src/main/asciidoc/appendix/settings.adoc, src/main/asciidoc/sql/SQL-Alter-Property.adoc
* Add new Datetime settings to Appendix Section 11.2 (see https://github.com/ArcadeData/arcadedb/issues/608)
* Update `ALTER PROPERTY` with `precision` attribute (see https://github.com/ArcadeData/arcadedb/issues/608)
* Fix links in Java reference Section 7.3
=> Datetime Updates

src/main/asciidoc/sql/SQL-Alter-Property.adoc, src/main/asciidoc/sql/SQL-Create-Property.adoc
* Added default value attribute to `CREATE PROPERTY` SQL command in Section 8.4
* Added default value attribute to `ALTER PROPERTY` SQL command in Section 8.4
=> Add default value attribute to create and alter property

src/main/asciidoc/sql/SQL-Insert.adoc, src/main/asciidoc/sql/SQL-Update.adoc
* SQL Insert in Section 8.4: Add note on unique inserts
* SQL Update in Section 8.4: Append UPSERT description
=> Refactor SQL Insert and Update docu parts

src/main/asciidoc/sql/SQL-Alter-Property.adoc, src/main/asciidoc/sql/SQL-Create-Property.adoc
* Add remark for `min` and `max` attributes in `CREATE PROPERTY`
* Add remark for `min` and `max` attributes in `ALTER PROPERTY`
* Add example for `default sysdate()` in `CREATE PROPERTY`
=> Update `CREATE PROPERTY` and `ALTER PROPERTY`

src/main/asciidoc/appendix/datatypes.adoc, src/main/asciidoc/sql/SQL-Functions.adoc, src/main/asciidoc/sql/SQL-Methods.adoc, src/main/asciidoc/sql/chapter.adoc
* Add geometric functions and methods to overview tables in Section 8
* Add geometric functions to Section 8.1
* Add geometric methods to Section 8.2
* Add shape datatypes to Section 11.1
* Fix example in `symmetricDifference` example in Section 8.1
=> Initial docu of geometric types

src/main/asciidoc/api/http.adoc
* Move endpoint list to beginning of section (similar to SQL section)
* Update example with create database to use server command
* Update server endpoint with info about accessibility of `list databases` command.
* Minor fixes
=> Update HTTP API section

src/main/asciidoc/api/http.adoc, src/main/asciidoc/sql/chapter.adoc
* Updates server-GET endpoint with description of optional `mode` parameter
* Fix SQL overview table
=> Server-GET endpoint update

src/main/asciidoc/api/graphql.adoc, src/main/asciidoc/api/gremlin.adoc, src/main/asciidoc/api/http.adoc, src/main/asciidoc/api/java-api.adoc, src/main/asciidoc/api/java-schema.adoc, src/main/asciidoc/api/mongo.adoc, src/main/asciidoc/api/postgres.adoc, src/main/asciidoc/api/redis.adoc, src/main/asciidoc/concepts/indexes.adoc, src/main/asciidoc/server/embed-server.adoc, src/main/asciidoc/sql/SQL-Alter-Property.adoc, src/main/asciidoc/sql/SQL-Alter-Type.adoc, src/main/asciidoc/version.adoc
* Update custom attribute type constraint in `ALTER TYPE`
* Update custom attribute type constraint in `ALTER PROPERTY`
* Fix heading sequences
* Fix passthrough attributes
* Fix numbered list
* Fix duplicate heading id
* Update version
=> Custom attribute type update and various fixes

src/main/asciidoc/api/http.adoc, src/main/asciidoc/sql/SQL-Import-Database.adoc
* Add note to `api/v1/query/` endpoint about constraint use of slashes `/`
* Update docu of `IMPORT DATABASE` SQL command with more info, new example and link
=> Update query endpoint and IMPORT DATABASE docu

src/main/asciidoc/appendix/community.adoc, src/main/asciidoc/concepts/basics.adoc, src/main/asciidoc/sql/SQL-Alter-Type.adoc, src/main/asciidoc/sql/SQL-Create-Index.adoc, src/main/asciidoc/sql/SQL-Functions.adoc
* Add reference to super types to type concepts section
* Remove unsupported syntax from `ALTER TYPE` command
* Remove ODB version note from `shortestPath` function
* Add note to `CREATE INDEX` command (@lvca please review if this is intended functionality)
* Add heading to community section in Appendix
* Add FAQ subsection in community section in the Appendix
=> Remove unsupported syntax from `ALTER TYPE`, add FAQ and minor fixes

src/main/asciidoc/api/http.adoc
* Add note about Windows curl use in HTTP API Section (https://github.com/ArcadeData/arcadedb/issues/513)
=> Add note about Windows curl use in HTTP API Section

src/main/asciidoc/api/http.adoc, src/main/asciidoc/appendix/requirements.adoc
* Added example for "list databases" server command of HTTP API
* Add issue links to Java requirements in appendix
=> Add example and add details

src/main/asciidoc/appendix/community.adoc, src/main/asciidoc/server/server.adoc, src/main/asciidoc/sql/SQL-Functions.adoc, src/main/asciidoc/sql/chapter.adoc, src/main/asciidoc/version.adoc
* Update version to 23.2.1
* Add reference entry for `sqrt` function in SQL Section
* Add subsection on server modes to Server Section
* Add Facebook link to Community Section
=> Recent updates (version, sqrt, server modes, fb link)

src/main/asciidoc/sql/SQL-Functions.adoc, src/main/asciidoc/sql/SQL-Methods.adoc
* Fixed `if()` function example ( see: https://github.com/ArcadeData/arcadedb/issues/921 )
* Fixed `asBoolean()` description
=> Function `if()` and method `asBoolean()` fixes

src/main/asciidoc/appendix/settings.adoc
* Add mongo settings introduced in https://github.com/ArcadeData/arcadedb/commit/b0a4528d73959c7e712ad15201c635a533cd54cf to the settings table
=> Add mongo settings

src/main/asciidoc/content.adoc, src/main/asciidoc/server/settings.adoc, src/main/asciidoc/version.adoc
* Update version (revnumber) to 23.3.1
* Added a JVM option to reduce GC induced memory latency (Section 4.2)
* Added project links to hot topics and made some mini changes (Section 1)
=> Version update and minor changes

src/main/asciidoc/sql/SQL-Methods.adoc, src/main/asciidoc/sql/chapter.adoc
* Added `asRID()` method to SQL method reference (Section 8.2)
* Fixed (and added `asRID` to) SQL Method Table (Section 8)
=> Add `asRID()` reference entry

src/main/asciidoc/api/redis.adoc
* Update transient commands with `EXISTS` command and use imperative phrasing (Section 7.12)
* Update permanent commands with `HEXISTS` command and use imperative phrasing (Section 7.12)
* Add misc command `PING` (Section 7.12)
=> Update Redis API commands reference

src/main/asciidoc/sql/SQL-Functions.adoc, src/main/asciidoc/sql/chapter.adoc, src/main/asciidoc/tools/console.adoc
* Add SQL table and reference entries for new functions `bool_and` and `bool_or` (Section 8)
* Add version substitution to console header (Section 6.1)
=> Add `bool_and` and `bool_or` functions and mini console fix

src/main/asciidoc/sql/SQL-Functions.adoc
* Update `encode` and `decode` SQL functions (Section 8.1)
=> Update encode and decode functions

src/main/asciidoc/appendix/chapter.adoc, src/main/asciidoc/appendix/graphs.adoc
* Add a section explaining graph databases to the Appendix (Section 11)
* @lvca Please review if the content and stype of writing are to your liking. Feedback welcome.
=> Add graph database section to appendix

src/main/asciidoc/sql/SQL-Functions.adoc, src/main/asciidoc/sql/SQL-Methods.adoc, src/main/asciidoc/sql/SQL-Where.adoc, src/main/asciidoc/sql/chapter.adoc
* Add `ifnull` method to SQL method table (Section 8)
* Change heading of `ifnull` function to ensure unique links (Section 8.1)
* Add `ifnull` reference entry (Section 8.2)
* Remove `column` from items table (Section 8.3)
=> Add `ifnull` method to docu

src/main/asciidoc/sql/SQL-Functions.adoc, src/main/asciidoc/sql/SQL-Methods.adoc, src/main/asciidoc/sql/chapter.adoc
* Sort SQL functions alphabetically in reference (Section 8.1)
* Add `format` SQL method to SQL overview table (Section 8)
* Minor SQL reference fixes (Section 8)
=> SQL reference fixes

src/main/asciidoc/api/http.adoc, src/main/asciidoc/appendix/settings.adoc, src/main/asciidoc/sql/SQL-Create-Index.adoc
* Add details about `GET` and `POST` variants of query endpoint (Section 7.5)
* Add exmaple for full text index to `CREATE INDEX` SQL statement (Section 8.4)
* Move settings table entry `server.httpsIncomingPort` down two rows for better readability (Section 11.2)
=> Some Details

src/main/asciidoc/appendix/sql-syntax.adoc, src/main/asciidoc/sql/SQL-Create-Index.adoc, src/main/asciidoc/sql/SQL-Where.adoc, src/main/asciidoc/sql/chapter.adoc, src/main/asciidoc/version.adoc
* Move `transform()` method in SQL overview to `collection` column (Section 8)
* Set link in "SQL FIltering" Section (8.3) to "SQL Bracket Filtering" Section in Appendix
* Fix syntax for "NOTE" in `CREATE INDEX` reference entry (Section 8.4)
* Update global version variable to `23.4.1`
=> Minor fixes and version update

src/main/asciidoc/sql/SQL-Functions.adoc, src/main/asciidoc/sql/SQL-Match.adoc, src/main/asciidoc/sql/SQL-Methods.adoc, src/main/asciidoc/sql/chapter.adoc
* Update overview tables for functions and methods (Section 8)
* Removed `decimal` function (Section 8.1)
* Added `duration` function (Section 8.1)
* Added `asByte` method (Section 8.2)
* Added `asDouble` method (Section 8.2)
* Added `asShort` method (Section 8.2)
* Added `lastIndexOf` method (Section 8.2)
* Added `precision` method (Section 8.2)
* Added comment on Cypher origin of `MATCH` (Section 8.4)
* Fixed headings in `MATCH` subection (Section 8.4)
=> SQL Function and Method Updates

src/main/asciidoc/appendix/managing-dates.adoc, src/main/asciidoc/sql/SQL-Functions.adoc, src/main/asciidoc/sql/SQL-Methods.adoc
* Update `duration` function (Section 8.1)
* Update `precision` method (Section 8.2)
* Add list of time units (Section 11.3)
=> Update Date(Time) Procedures

src/main/asciidoc/sql/SQL-Functions.adoc, src/main/asciidoc/sql/chapter.adoc
* Added docu for `randomInt` function (Section 8.1)
=> Reference entry for `randomInt` function

src/main/asciidoc/concepts/basics.adoc
* Added subsection on record retrieval complexity (Section 3.1)
* Added subsection on graph traversal complexity (Section 3.4)
See #166
=> Add O(1) complexity details

src/main/asciidoc/version.adoc
* Updated global version variable
=> Update version to 23.5.1

src/main/asciidoc/api/postgres.adoc
* Add infos to Postgres client (`psql`) section (Section 7.6.4)
=> Update Postgres Client Section

src/main/asciidoc/appendix/chapter.adoc, src/main/asciidoc/appendix/vectors.adoc, src/main/asciidoc/concepts/basics.adoc, src/main/asciidoc/content.adoc, src/main/asciidoc/introduction/multimodel.adoc, src/main/asciidoc/sql/SQL-Create-Index.adoc, src/main/asciidoc/sql/SQL-Functions.adoc, src/main/asciidoc/sql/chapter.adoc, src/main/asciidoc/tools/importer.adoc
* Add "Vector" Subsection to Appendix (Section 11)
* Add `vectorNeighbors` function to SQL overview and reference (Section 8, Section 8.1) 
* Add new importer parameters to Importer setting table (Section 6.4)
* Add `HNSW` to `CREATE INDEX` docu (Section 8.4)
* Rename "Vector Embedding" to "Vector" in Introduction (Section 1)
* Fix typo (Section 3.5)
=> Initial vector model docu

src/main/asciidoc/introduction/multimodel.adoc, src/main/asciidoc/sql/SQL-Methods.adoc, src/main/asciidoc/sql/chapter.adoc, src/main/asciidoc/tools/importer.adoc
* Add `asRecord` method to overview table (Section 8)
* Add `asRecord` method to reference (Section 8.2)
* Add short paragrsph about configurability (Section 2.2.6)
* Add default values to importer settings table (Section 6.4.1)
=> Add `asRecord` method and minor vector additition

src/main/asciidoc/api/java-events.adoc, src/main/asciidoc/concepts/basics.adoc, src/main/asciidoc/introduction/multimodel.adoc, src/main/asciidoc/sql/SQL-Create-Property.adoc
* Improve distance function table (Section 2.2.6)
* Add paragrpah on edge constraints (Section 3.4)
* Add before and after read listener (Section 7.2.7)
* Add embedded type constraint to SQL `CREATE PROPERTY` (Section 8.4)
=> Various updates following recently added features

src/main/asciidoc/appendix/requirements.adoc, src/main/asciidoc/security/chapter.adoc, src/main/asciidoc/security/secrets.adoc
* Add section "Handling Secrets" (Section 9)
* Add note on "headless" JRE (Section 11.9)
=> Add subsection about secrets to security section

src/main/asciidoc/introduction/run.adoc
Add local installation instruction using
- manual
- scoop on windows
- open mac os x section, todo for now
=> Add scoop installer instructions

src/main/asciidoc/content.adoc, src/main/asciidoc/introduction/multimodel.adoc, src/main/asciidoc/server/docker.adoc
* Update hot topics info (Section 1)
* Add search engine model summary (Section 2.2.4)
* Update Docker Section (Section 4.5)
* use `--name` Docker parameter
* add Podman compatibility
=> Search engine model and docker update

src/main/asciidoc/sql/SQL-Methods.adoc
* Updated `type()` method reference entry (Section 8.2)
=> Update type method reference entry

src/main/asciidoc/introduction/multimodel.adoc, src/main/asciidoc/sql/SQL-Methods.adoc, src/main/asciidoc/sql/chapter.adoc
* Add comment about order of edges (Section 2.2.1)
* Add reference entry for `capitalize()` SQL method (Section 8.2)
=> Edge order and capitalize method

src/main/asciidoc/comparison/orientdb.adoc, src/main/asciidoc/introduction/run.adoc, src/main/asciidoc/server/docker.adoc, src/main/asciidoc/server/settings.adoc
* Rework "Run ArcadeDB" practical subsection (Section 2.3.1)
* Add comment about memory configuration in containers (Section 4.2.1)
* Add hostname to Docker run command (Section 4.5)
* Prepare "Comparison" Section for further entries by making subsections listed in ToC (Section 10)
=> Various minor updates

src/main/asciidoc/appendix/community.adoc
* Add item to FAQ about SQL injection (Section 11)
=> Add item to FAQ about SQL injection

src/main/asciidoc/introduction/multimodel.adoc, src/main/asciidoc/introduction/run.adoc, src/main/asciidoc/introduction/what-is-arcadedb.adoc
* improving read flow, minor language fixes, fix typos, fix spacings etc (Section 2)
=> Many minor fixes for Section 2

src/main/asciidoc/sql/SQL-Introduction.adoc
* Add paragraph on system types (Section 8)
=> Add paragraph on system types

src/main/asciidoc/appendix/settings.adoc, src/main/asciidoc/concepts/basics.adoc, src/main/asciidoc/concepts/indexes.adoc, src/main/asciidoc/concepts/inheritance.adoc
* Fix typos (Section 3)
* Added `ha.serverRole` to settings table (Section 11.2)
* Added `server.httpsIoThreads` to settings table (Section 11.2)
=> Add new settings

src/main/asciidoc/api/chapter.adoc, src/main/asciidoc/api/python.adoc
* Add Python drivers to API Chapter overview (Section 7)
* Add Python section stub (Section 7)
=> Some Python Preparations

src/main/asciidoc/appendix/sql-syntax.adoc, src/main/asciidoc/sql/SQL-Drop-Index.adoc, src/main/asciidoc/sql/SQL-Script.adoc, src/main/asciidoc/sql/SQL-Update.adoc
* Add example of appending collection with `UPDATE` (Section 8.2)
* Fix `DROP INDEX` example (Section 8.2)
* Add note on LET as view (Section 8.5)
* Remove `Set` from collection types in appendix (Section 11.5)
=> Minor SQL update

src/main/asciidoc/api/chapter.adoc, src/main/asciidoc/api/java-api.adoc
* Uncomment "native-select" Section (Section 7)
* Move Java Remote API Section include into Java API doc (Section 7)
* Rearrange API sections such that Local and Remote are next to each other (Section 7)
* Rename "Java API (Embedded)" to "Java API (Local)" (Section 7)
=> Add native-select and Java API refactor

src/main/asciidoc/api/http.adoc, src/main/asciidoc/sql/SQL-Create-Property.adoc, src/main/asciidoc/tools/console.adoc
* Added note on transactions for scripts (Section 6.1)
* Added note on LINK properties in `CREATE PROPERTY` (Section 8.2)
* Minor grammar fix (Section 7.7)
=> Adding notes

src/main/asciidoc/api/http-csharp.adoc, src/main/asciidoc/api/http-elixir.adoc, src/main/asciidoc/api/http-nodejs.adoc, src/main/asciidoc/appendix/sql-syntax.adoc, src/main/asciidoc/sql/SQL-Console.adoc, src/main/asciidoc/sql/SQL-Methods.adoc, src/main/asciidoc/sql/chapter.adoc
* Update SQL Chapter Overview (Section 8)
* Add SQL `CONSOLE` command (Section 8.1)
* Add SQL `field` method (Section 8.4) [Ill update this ref entry as soon as I figure out how other property types work]
* Update SQL reserved keywords (Section 11.5)
* Update HTTP-API language sections (Section 7.8--7.10)
=> Add "new"  SQL command and method

src/main/asciidoc/tools/console.adoc, src/main/asciidoc/tools/importer.adoc
* Add console command overview (Section 6.1)
* Update console help output (Section 6.1)
* Add `mapping` stub to importer settings table (Section 6.4)
* Add `probeOnly` to importer settings table (Section 6.4)
=> Importer and Console Update

src/main/asciidoc/api/chapter.adoc, src/main/asciidoc/api/http.adoc, src/main/asciidoc/appendix/sql-syntax.adoc, src/main/asciidoc/sql/SQL-Where.adoc, src/main/asciidoc/tools/console.adoc, src/main/asciidoc/tools/upgrade.adoc, src/main/asciidoc/version.adoc
* Add group option to create user (Section 6.1)
* Fix Link (Section 6.5)
* Add header row and column to API overview table (Section 7)
* Improve intro text (Section 7.7)
* Fix inline literals in filtering tables (Section 8.1)
* Fix SQL comment description (Section 11.5)
* Update version variable to 23.12.1
=> Miscellaneous Fixes

src/main/asciidoc/appendix/settings.adoc, src/main/asciidoc/introduction/run.adoc, src/main/asciidoc/server/server.adoc, src/main/asciidoc/sql/SQL-Import-Database.adoc, src/main/asciidoc/tools/console.adoc, src/main/asciidoc/tools/importer.adoc
* Add bullet about hardware compatbility (Section 2.3)
* Update server console output (Section 4.1)
* Add note about multiline comments in console (Section 6.1)
* Add note about `probeOnly` usage (Section 6.4)
* Add example for `probeOnly` (Section 8.2)
* Add `warningsEvery` setting to settings table (Section 11.2)
=> Various updates

src/main/asciidoc/sql/SQL-Methods.adoc, src/main/asciidoc/sql/chapter.adoc, src/main/asciidoc/version.adoc
* Add SQL `sort` method (Section 8.4)
* Update version to 24.1.1
=> Add SQL "sort" method (and version update)

src/main/asciidoc/appendix/sql-syntax.adoc, src/main/asciidoc/sql/SQL-Introduction.adoc
* Clarify SQL case sensitivity (Section 11.5)
* Softer ramp on for SQL intro (Section 8)
=> SQL Update

src/main/asciidoc/api/tools.adoc, src/main/asciidoc/sql/SQL-Move.adoc, src/main/asciidoc/sql/chapter.adoc
* Fix typo (Section 7.18)
* Add `MOVE VERTEX` command (Section 8.2)
* Change heading (Section 8)
=> Add "MOVE VERTEX" Command

src/main/asciidoc/sql/SQL-Methods.adoc, src/main/asciidoc/sql/chapter.adoc
* Add entry for `ifempty` method in SQL reference (Section 8.4)
=> Add "ifempty" reference entry

src/main/asciidoc/appendix/sql-syntax.adoc, src/main/asciidoc/sql/SQL-Methods.adoc, src/main/asciidoc/sql/SQL-Where.adoc
* Various fixes to SQL filtering (Section 8.1)
* Add note to SQL `length` method (Section 8.4)
* Add var num arguments to `append` method (Section 8.4)
* Add `@this` and `@size` to reserved identifiers (Section 11.5)
=> Add note to length method

src/main/asciidoc/server/settings.adoc, src/main/asciidoc/sql/SQL-Import-Database.adoc
* Add env var table (Section 4.2)
* Add csv graph import example (Section 8.2)
=> Add server-relevant environment variables table

src/main/asciidoc/sql/SQL-Methods.adoc, src/main/asciidoc/sql/chapter.adoc
* Add `asJSON`, remove `toJSON` from overview (Section 8)
* Move `toJSON` to `asJSON` in reference (Setion 8.4)
* Update `asBoolean` reference entry (Section 8.4)
=> Add "asJSON", remove "toJSON"

src/main/asciidoc/version.adoc
* Update version variable to '24.4.1'
=> Update version to 24.4.1

src/main/asciidoc/server/docker.adoc, src/main/asciidoc/server/ha.adoc, src/main/asciidoc/sql/SQL-Introduction.adoc, src/main/asciidoc/sql/SQL-Methods.adoc, src/main/asciidoc/sql/SQL-Projections.adoc, src/main/asciidoc/sql/SQL-Script.adoc, src/main/asciidoc/sql/chapter.adoc
* Added SQL method reference entry for `join` (Section 8.4)
* Added note on `RETURN` (Section 8.5)
* Minor fixes (Section 4)
* Minor fixes (Section 8)
=> Add "join" method reference entry

src/main/asciidoc/api/postgres.adoc, src/main/asciidoc/appendix/graphs.adoc, src/main/asciidoc/appendix/sql-syntax.adoc, src/main/asciidoc/sql/SQL-Introduction.adoc
* Add note about debug option (Section 7.11)
* Complete comparison operator reference (Section 11.5)
* Make graph render (Section 11.6)
=> Comparison operator reference and minor fixes

src/main/asciidoc/api/redis.adoc
* Remove manual index name from automatic index creation (Section 7.17)
=> Fix Redis example

src/main/asciidoc/api/chapter.adoc, src/main/asciidoc/api/java-api-remote.adoc, src/main/asciidoc/api/java-ref-database-async.adoc, src/main/asciidoc/api/java-ref-database-factory.adoc, src/main/asciidoc/api/java-ref-database.adoc, src/main/asciidoc/server/embed-server.adoc
* Fix XML syntax highlighting and ersion insert (Section 4.4)
* Fix Note block (Section 4.4)
* Add Typescript Driver (Section 7)
* Add dividers to Java Reference (Section 7.4)
* Add method table (Section 7.4)
=> Various API Updates

src/main/asciidoc/api/chapter.adoc, src/main/asciidoc/api/java-tutorial.adoc, src/main/asciidoc/introduction/multimodel.adoc, src/main/asciidoc/sql/SQL-Methods.adoc
* Add bullet on vertex labels (Section 2.2.1)
* Add WIP PHP driver to list (Section 7)
* Use consistent code block syntax (Section 7.2.1)
* Add examples for `remove` and `removeAll` methods (Section 8.4)
=> Miscellaneous Changes

src/main/asciidoc/appendix/community.adoc, src/main/asciidoc/content.adoc, src/main/asciidoc/sql/SQL-Methods.adoc, src/main/asciidoc/version.adoc
* Update version to 24.6.1
* Clarify native query language (Section 1)
* Fix `asJSON` entry (Section 8.4)
* Add intro book to FAQ (Section 11.10)
=> Small Updates

src/main/asciidoc/sql/SQL-Script.adoc
simple fix to make docs render correctly again.
=> fix unterminated code block

src/main/asciidoc/sql/SQL-Methods.adoc, src/main/asciidoc/sql/chapter.adoc
* Add `trimPrefix` and `trimSuffix` SQL methods (Section 8.4)
=> Add trimPrefix and trimSuffix methods

src/main/asciidoc/api/chapter.adoc, src/main/asciidoc/api/clojure.adoc, src/main/asciidoc/api/java-tutorial.adoc, src/main/asciidoc/tools/console.adoc
* Add Clojure tutorial (Section 7)
* Fix Gremlin version (Section 7.2.1)
* Amplify comment rules for console (Section 6.1)
=> Add Clojure Tutorial

src/main/asciidoc/api/clojure.adoc, src/main/asciidoc/api/java-ref-database.adoc, src/main/asciidoc/appendix/sql-syntax.adoc, src/main/asciidoc/sql/SQL-Projections.adoc, src/main/asciidoc/sql/SQL-Script.adoc, src/main/asciidoc/studio/graph.adoc
* Fix Table (Section 5)
* Fix Table (Section 7)
* Add example for starting ArcadeDB server from Clojure (Section 7.6)
* Add example for nested projection field renaming (Section 8)
* Add note about atomicity of SQLscript (Section 8.5)
* Add section on nested projections (Section 11.5)
=> Some extensions

pom.xml, src/main/asciidoc/appendix/settings.adoc, src/main/asciidoc/server/server.adoc, src/main/asciidoc/sql/SQL-Import-Database.adoc, src/main/asciidoc/tools/importer.adoc, src/main/asciidoc/version.adoc
* Update version in `pom.xml`
* Update version variable to 25.1.1
* Add section about server metrics (Section 4.1)
* Add JSONL to importer formats (Section 6.4)
* Add JSONL to SQL `IMPORT DATABASE` command formats (Section 8.2)
* Add `serverMetrics` settings and Prometheus plugin (Section 11.2)
=> 25.1.1 Updates

src/main/asciidoc/api/http.adoc, src/main/asciidoc/sql/SQL-Delete.adoc, src/main/asciidoc/sql/SQL-Functions.adoc, src/main/asciidoc/sql/SQL-Where.adoc
* Make studio serializer docu explicit (Section 7.8)
* Add note about default formatting of the sysdate function (Section 8.3)
* Add note about s modifier to MATCHES filter (Section 8.1)
* Fix SQL DELETE sub lists (Section 8.2)
=> Improvements resulting from issues

src/main/asciidoc/server/kubernetes.adoc, src/main/asciidoc/sql/SQL-Check-Database.adoc, src/main/asciidoc/version.adoc
* Add subsection about Helm charts (Section 4.6)
* Add `COMPRESS` variant to `CHECK DATABASE` SQL command (Section 8.2)
* Update version constant to 25.3.1
=> Update to 25.3.1

src/main/asciidoc/appendix/community.adoc, src/main/asciidoc/appendix/datatypes.adoc, src/main/asciidoc/introduction/run.adoc, src/main/asciidoc/introduction/what-is-arcadedb.adoc
* Minor fixes (Section 2)
* Add remark about `MAP` vs `EMBEDDED` (Section 11.1)
* Add question about schemas to FAQ (Section 11.10)
=> Some Updates

src/main/asciidoc/concepts/basics.adoc, src/main/asciidoc/concepts/indexes.adoc, src/main/asciidoc/concepts/schema.adoc, src/main/asciidoc/concepts/transactions.adoc, src/main/asciidoc/version.adoc
* Minor fixes in Section 3
* Update version to 25.4.1
=> Chapter 3 fixes and version update

src/main/asciidoc/server/docker.adoc, src/main/asciidoc/server/embed-server.adoc, src/main/asciidoc/server/ha.adoc, src/main/asciidoc/server/kubernetes.adoc, src/main/asciidoc/server/server.adoc, src/main/asciidoc/server/settings.adoc, src/main/asciidoc/sql/chapter.adoc, src/main/asciidoc/sql/sql-functions.adoc
* Minor language fixes in Section 4.
* Add reference entry for SQL function `ifempty` (Section 8.3)
@robfrank Could you check if Line 3 in the code block in https://docs.arcadedb.com/#_logging is correct, it seems to deviate from the description below.
=> Add ifempty entry and language fixes Sec 4

src/main/asciidoc/api/http.adoc, src/main/asciidoc/api/java-api.adoc, src/main/asciidoc/appendix/requirements.adoc, src/main/asciidoc/appendix/settings.adoc, src/main/asciidoc/concepts/basics.adoc
* Fix async setting default value (Section 11.2)
* Fix setting reference (Section 11.2)
* Add reference to async settings (Setting 7.2)
* Add reference to async settings (Setting 7.8)
* Add link to Java 17 section of README (Section 11.9)
=> Async related updates

src/main/asciidoc/api/http.adoc, src/main/asciidoc/appendix/requirements.adoc, src/main/asciidoc/appendix/settings.adoc, src/main/asciidoc/appendix/sql-syntax.adoc, src/main/asciidoc/server/settings.adoc, src/main/asciidoc/sql/sql-projections.adoc
* Added `retries` property to command endpoint payload (Section 7.8)
* Add example for nested projection (Section 8)
* Added `@props` to SQL syntax (Section 11.5)
* Added `bucketReuseSpaceMode` to settings (Section 11.2)
* Uncommented `txWalFiles` to settings (Section 11.2)
* Fix settings table (Section 11.2)
* Fix internal link (Section 11.9)
=> SQL Updates

src/main/asciidoc/sql/sql-script.adoc
* Add `LOCK` statement to SQL Script overview (Section 8.5)
=> Add lock statement to sql script section

src/main/asciidoc/reference/datatypes.adoc
* Add warning about float serialization (Section 11.3)
* remove left-over empty files
*
=> Add note about JSON serialization

src/main/asciidoc/query-languages/sql/sql-functions.adoc
* Refactor SQL Functions Section (Section 8.3)
=> Improve SQL Functions
