ArcadeData/arcadedb-docs

src/main/asciidoc/api/http.adoc
I found a couple of minor typos and corrected them.
Additionally, in the example documentation for `query`, the setup description for the parameter-based query mentioned performing an update (a non-idempotent statement) but the example's contents were a select statement (which is idempotent).  I updated the setup description to reflect what the query was doing.
=> Fix minor typos and incorrect setup description for example

src/main/asciidoc/api/http.adoc
In the `curl` example for using parameters with SQL, fix the JSON body that is provided in the example so that it quotes the `params` identifier.
=> Fix unquoted params value in curl example

src/main/asciidoc/api/http.adoc
Added comment to `server` endpoint reference in HTTP/JSON Protocol / Reference (7.2.1), paraphrasing https://github.com/ArcadeData/arcadedb/issues/528#issuecomment-1255525603 .
=> Added comment to server-endpoint reference

src/main/asciidoc/api/java-schema.adoc
updated `keyTypes` per:
https://github.com/ArcadeData/arcadedb/blob/27bbbaf78955ddc60bc905bb73cd17c586f17692/engine/src/main/java/com/arcadedb/schema/Schema.java#L77
=> fixes `keyTypes` type in createManualIndex documentation

src/main/asciidoc/appendix/settings.adoc, src/main/asciidoc/appendix/sql-syntax.adoc, src/main/asciidoc/introduction/run.adoc, src/main/asciidoc/server/chapter.adoc, src/main/asciidoc/sql/SQL-Functions.adoc, src/main/asciidoc/sql/SQL-Insert.adoc, src/main/asciidoc/sql/SQL-Methods.adoc, src/main/asciidoc/sql/SQL-Select.adoc, src/main/asciidoc/sql/SQL-Update.adoc, src/main/asciidoc/sql/SQL-Where.adoc
* made subheadings, particularly **Examples** consistent in Sec. 8
* fixed more malformed lists
* added a link to a java docu listing hash algorithms
* formatted code in tables with literal monospace, ie variables, short code examples
---
* Added table listing binaries to Sec. 2
=> Sec 8 (SQL) and Appendix fixes

src/main/asciidoc/api/java-schema.adoc
* corrects the creation API methods from `createClassIndexes` to `createTypeIndex`
* includes additional `createTypeIndex` overload method signatures
* other notes on index creation and exceptions
* notes on creating indexes for Edge types
=> adds more information on creating indexes via the Schema java API.

src/main/asciidoc/api/http.adoc, src/main/asciidoc/tools/importer.adoc
Checking the network requests of the studio I found out that "sqlscript" as used as value for the language key of the command endpoint POST request, thus I added this to the documentation in Section 7.4.
=> Add sqlscript as language option

src/main/asciidoc/api/chapter.adoc, src/main/asciidoc/api/http.adoc, src/main/asciidoc/sql/SQL-Insert.adoc
* Added my **CHICKEN Scheme** to the driver table
* Fixed typo in SQL `INSERT INTO` example
* Added `-I` to `begin` HTTP API request example so session-ID is returned
=> CHICKEN Scheme driver, typo, and HTTP example

src/main/asciidoc/api/http.adoc, src/main/asciidoc/sql/SQL-Check-Database.adoc, src/main/asciidoc/tools/console.adoc
* Added subsection on implicit transaction when using `sqlscript` to Sectipn 7.4
* Added table explaining returned fields from `CHECK DATABASE` SQL command
* Added `set language` command to console overview in Section 6.1
Please review https://github.com/ArcadeData/arcadedb-docs/issues/88#issuecomment-1338073497 before merging, as there are some fields in `CHECK DATABASE` that are still unclear.
Thank you
=> `sqlscript` section, `CHECK DATABASE` fields, `set language` console command

src/main/asciidoc/api/http.adoc, src/main/asciidoc/api/mongo.adoc, src/main/asciidoc/tools/console.adoc
* Added `user` endpoints docu to HTTP API Section
* Added `ready` endpoint docu to HTTP API Section
* Added `created user` command to console command overview and added example in Console Section
* Resorted endpoints in docu in HTTP API Section
* Added MQL link to Mongo API Section
=> `user` and `ready` endpoints, `create user` console command, resort endpoints, add mql docu link

src/main/asciidoc/server/embed-server.adoc
To run an embedded server the arcadedb-server dependency needs to be added.
=> server dependency in addition to engine

src/main/asciidoc/api/http.adoc
In Section 7.4 HTTP/JSON Protocol:
* Adds `server` POST endpoint with `shutdown` command and example
* Removes deprecated `create` and `load` document endpoints docu
=> Added server POST endpoint and remove deprecated document endpoints

src/main/asciidoc/api/gremlin.adoc
It took me a while to find out which additional libraries are required to include the gremlin-plugin without errors. Being more specific about the needed jars might also help other users.
=> More specific about gremlin libs

pom.xml, src/main/asciidoc/api/graphql.adoc, src/main/asciidoc/api/gremlin.adoc, src/main/asciidoc/api/java-api.adoc, src/main/asciidoc/api/mongo.adoc, src/main/asciidoc/api/postgres.adoc, src/main/asciidoc/api/redis.adoc, src/main/asciidoc/server/embed-server.adoc, src/main/asciidoc/version.adoc
The mentioning of arcadedb versions were not consistent. Updated all to 23.1.1.
=> increase the references to ArcadeDB versions consistently up to 23.1.1

src/main/asciidoc/sql/SQL-Export-Database.adoc
* Removed quotation marks from arguments of `FORMAT` component of `EXPORT DATABASE` statement (SQL Section)
=> Remove quot marks from FORMAT argument of EXPORT DATABASE (SQL)

src/main/asciidoc/sql/SQL-Where.adoc
* Make case sensitivity of `LIKE` operator explicit
* Make examples in operator table consistent in formatting
=> SQL Filtering Fixes (Section 8.3)

src/main/asciidoc/security/groups.adoc
* Added `appendonly` group example to Security Section (Section 9)
* This may resolve [Append-only buckets](https://github.com/ArcadeData/arcadedb/issues/13)?
=> Added `appendonly` group example

src/main/asciidoc/appendix/settings.adoc, src/main/asciidoc/sql/SQL-Functions.adoc
* Added entry for `backupDirectory` setting in settings table (Section 11.2)
* Moved `databaseDirectory` setting to other `server.*` settings (Section 11.2)
* Added note to reference entry for special `expand()` function (Section 8.1)
=> `backupDirectory` and `expand`

src/main/asciidoc/api/http.adoc, src/main/asciidoc/appendix/sql-syntax.adoc, src/main/asciidoc/sql/SQL-Functions.adoc, src/main/asciidoc/sql/SQL-Methods.adoc, src/main/asciidoc/sql/SQL-Where.adoc, src/main/asciidoc/sql/chapter.adoc
* Remove leftover `open` and `close` endpoint HTTP-API reference entries (Section 7.5)
* Add note on `query` endpoint regarding question marks
* Add new functions and methods to SQL overview tables (Section 8)
* Add note on escaping percent symbols in `format function` in SQL function reference (Section 8.1)
* Add `concat` function to SQL function reference (Section 8.1)
* Add example to `exclude` function to SQL function reference (Section 8.1)
* Add `split` and `transform` methods to SQL method reference (Section 8.2)
* Add `ILIKE` to SQL filtering operators table (Section 8.3)
* Add `ILIKE` to SQL syntax appendix (Section 11.5)
=> HTTP and SQL Updates

src/main/asciidoc/api/http.adoc, src/main/asciidoc/appendix/sql-syntax.adoc
* Add example for POST method with `query` endpoint (Section 7.5)
* Add POST method entry to HTTP API table (Section 7.5)
* Add `@cat` to reserved property names (Section 11.5)
=> Add query endpoint example

src/main/asciidoc/api/cypher.adoc, src/main/asciidoc/content.adoc, src/main/asciidoc/introduction/multimodel.adoc, src/main/asciidoc/sql/SQL-Introduction.adoc, src/main/asciidoc/sql/SQL-Traverse.adoc, src/main/asciidoc/sql/chapter.adoc
* Added new models to Multimodel Section introduction (Section 2.2)
* Added stub sections for new models (Section 2.2)
* Add links to github issues in coming soon sections (Time-Series and Vector-Embedding)
* Add links to new models in Section 1
* Fix heading hierarchy in Cypher API section (Section 7.8)
* Add link to (updated) SQL cheat sheet to SQL Introduction section (Section 8)
* Add section on traversal strategies to Traverse command reference entry (Section 8.4)
=> Keeping Docs in Step with new Models

src/main/asciidoc/appendix/sql-syntax.adoc, src/main/asciidoc/sql/SQL-Create-Index.adoc
* Added note about multiple property fulltext indexes to `CREATE INDEX` reference entry (Section 8.4)
* Added `@in` and `@out` to reserved identifiers (Section 11.5)
=> Mini Update

src/main/asciidoc/sql/SQL-Methods.adoc
* Added note on behavior of float values when applied to the `asInteger` method (Section 8.2)
=> Add note on floats to asInteger

src/main/asciidoc/sql/SQL-Export-Database.adoc, src/main/asciidoc/sql/SQL-Introduction.adoc
* Updated `EXPORT DATABASE` command after https://github.com/ArcadeData/arcadedb/issues/649 (Section 8.4)
* Added link in "No JOINs" paragraph to "Nested Projections" paragraph in SQL Introduction (Section 8)
=> Update SQL Docu

src/main/asciidoc/sql/SQL-Create-Property.adoc, src/main/asciidoc/tools/console.adoc
* Fix position of remark on supported types in SQL `CREATE PROPERTY` (Section 8.4)
* Clean up, add example for arument passed scripting and make console section more consistent (Section 6.1)
=> Minor Fixes in SQL `CREATE PROPERTY` and clean up in console section

src/main/asciidoc/introduction/run.adoc
During last contribution we overlooked a typo in install instructions.
=> fix typo in scoop installer instructions

src/main/asciidoc/api/http.adoc, src/main/asciidoc/concepts/inheritance.adoc, src/main/asciidoc/tools/console.adoc, src/main/asciidoc/version.adoc
* Update method name from `addParent()` to `addSuperType()` (Section 3.7) 
* Add paragraph about console-server interaction (Section 6.1)
* Add missing HTTP API server commands (Section 7.5)
* Make `curl` HTTP API examples copy-pasteable (Section 7.5)
* Update version to `23.7.1`
=> Fix docs issues

src/main/asciidoc/api/http.adoc, src/main/asciidoc/version.adoc
Section 7.5:
* Added list of potential HTTP response status codes to each endpoint.
* Added paragraph on general response structure and status code.
* Removed example using outdated `document` endpoint.
* Made examples more consistent.
* Added version variable to response examples where applicable.
---
* Updated global version variable to 23.9.1
=> Update HTTP API Docu

src/main/asciidoc/api/http.adoc, src/main/asciidoc/sql/SQL-Create-Vertex.adoc, src/main/asciidoc/sql/SQL-Insert.adoc
* (Re-)added `databases` endpoint reference entry (Section 7.5)
* Make `SQL INSERT` reference entry more consistent (Section 8.4)
* Add syntax and example for multiple `CONTENT` (JSON) `INSERT`s (Section 8.4)
* Add syntax and example for multiple `CONTENT` (JSON) `CREATE VERTEX`es (Section 8.4)
=> HTTP and INSERT Update

pom.xml, src/main/asciidoc/concepts/basics.adoc, src/main/asciidoc/manual.adoc, src/main/asciidoc/sql/SQL-Drop-Type.adoc, src/main/asciidoc/sql/SQL-Insert.adoc, src/main/asciidoc/sql/SQL-Rebuild-Index.adoc, src/main/asciidoc/sql/SQL-Script.adoc, src/main/asciidoc/sql/SQL-Update.adoc
* Fix Typo in `DROP TYPE` (Section 8.2)
* Remove incompatible example from `INSERT INTO` regarding edges (Section 8.2)
* Add note on necessity to `REBUILD INDEX` (Section 8.2)
* Add remark on removing properties from records to `UPDATE` (Section 8.2)
* Remove syntax constraint from SQL Script `IF` (Section 8.5)
* Add remark on argument of SQL Script `FOREACH` (Section 8.5)
* Add remark on buckets of sub-types (Section 3.3)
* Add remark on referenced relationships not being edges (Section 3.4)
* Move version include above title in `manual.adoc` to make Version rendered as subtitle, https://github.com/ArcadeData/arcadedb-docs/issues/216
* Update version in `pom.xml`
=> Mostly SQL improvements and version in manual title page

src/main/asciidoc/api/http.adoc, src/main/asciidoc/api/java-api-remote.adoc, src/main/asciidoc/api/java-tutorial.adoc, src/main/asciidoc/api/native-select.adoc, src/main/asciidoc/server/server.adoc
* Use consistent source code blocks (Section 4)
* Add note on `defaultDatabases` without user creation (Section 4.1.3)
* Fix paths to monospace (Section 7.2.1)
* Use `{revnumber}` in `pom` excerpt (Section 7.4)
* Add `awaitResponse` parameter to HTTP API `command` (Section 7.6)
* Add initial "native-select" docu (not publicly visible)
=> Update HTTP API and initial native-select docu

src/main/asciidoc/appendix/settings.adoc, src/main/asciidoc/security/secrets.adoc, src/main/asciidoc/server/server.adoc
* Add example for using `rootPasswordPath` setting (Section 4.1)
* Update secrets handling advise by mentioning `rootPasswordPath` setting (Section 9.4)
* Add `rootPasswordPath` to settings table (Section 11.2)
=> Document `rootPasswordPath` Setting

src/main/asciidoc/api/gremlin.adoc, src/main/asciidoc/api/http.adoc, src/main/asciidoc/api/postgres.adoc, src/main/asciidoc/concepts/basics.adoc, src/main/asciidoc/server/docker.adoc
* Add paragraph about edge relationships (Section 3.4)
* Add subsection about persistence to Docker section (Section 4.5)
* Add `params` optional property bullet to POST-method `query` endpoint (Section 7.7)
* Replace Python Postgres with`psycopg2` (Section 7.11) 
* More precise server call (Section 7.14)
=> Fixes and Extensions

src/main/asciidoc/api/http.adoc, src/main/asciidoc/api/java-api-remote.adoc, src/main/asciidoc/appendix/settings.adoc, src/main/asciidoc/concepts/basics.adoc, src/main/asciidoc/concepts/inheritance.adoc, src/main/asciidoc/server/docker.adoc, src/main/asciidoc/server/embed-server.adoc, src/main/asciidoc/server/ha.adoc, src/main/asciidoc/server/kubernetes.adoc, src/main/asciidoc/server/server.adoc, src/main/asciidoc/server/settings.adoc, src/main/asciidoc/sql/SQL-Introduction.adoc, src/main/asciidoc/tools/console.adoc, src/main/asciidoc/tools/importer.adoc, src/main/asciidoc/tools/json-importer.adoc, src/main/asciidoc/tools/neo4j-importer.adoc, src/main/asciidoc/tools/orientdb-importer.adoc, src/main/asciidoc/tools/restore.adoc
* Shell type source blocks all start with `$` (Section 3,4,6,7)
* Console source blocks all start with `>` (Section 3,4,6)
* SQL blocks use all caps commands (Section 3,4,6)
* Prepend database name in console blocks where needed (Section 6)
* Make ASCII diagrams render via ditaa (Section 3)
* Add small table comparing differences of Postgres with ArcadeDB SQL (Section 8)
* Fix https://github.com/ArcadeData/arcadedb-docs/issues/261 (Section 7.3.1)
=> Make source blocks more consistent, add small SQL translation table, render ASCII diagrams

src/main/asciidoc/server/embed-server.adoc
The document talks about adding embedded server dependency but does not tell the user that the studio url will not be accessible. The arcadedb studio can be accessed after additional dependency `arcade-studio` is added. See my stackoverflow question to see more information on this - https://stackoverflow.com/questions/78329249/arcadedb-studio-when-starting-embedded-server
=> Added information on how to add studio for embedded server.

src/main/asciidoc/api/java-api-remote.adoc, src/main/asciidoc/api/java-ref-database-factory.adoc, src/main/asciidoc/api/java-tutorial.adoc, src/main/asciidoc/appendix/community.adoc, src/main/asciidoc/appendix/managing-dates.adoc, src/main/asciidoc/sql/SQL-Introduction.adoc, src/main/asciidoc/sql/SQL-Select.adoc
* Use consistent names in Java tutorial (Section 7.2)
* Use default port in Java tutorial (Section 7.3)
* Fix typo in Java reference (Section 7.4)
* Add discussion about special SQL functions (Section 8)
* Add DISTINCT to SELECT reference entry (Section 8.2)
* Fix link (Section 11.3)
* Add entry about consecutive identifiers to FAQ (11.10)
=> Various fixes and additions

src/main/asciidoc/sql/SQL-Console.adoc, src/main/asciidoc/sql/SQL-Create-Property.adoc, src/main/asciidoc/sql/SQL-Create-Vertex.adoc
* Add tip to `CONSOLE` statement (Section 8.2)
* Improve `CREATE PROPERTY` statement description (Section 8.2)
* Fix `CREATE VERTEX` example (Section 8.2)
=> Some SQL Statement Improvements

src/main/asciidoc/appendix/managing-dates.adoc, src/main/asciidoc/sql/sql-functions.adoc
* Fix sysdate function ref entry (Section 8.3)
* Make function ref entries more consistent (Section 8.3)
* Fix link to format method (Section 11.3)
See https://github.com/ArcadeData/arcadedb/issues/1958
=> Fix "sysdate" function reference entry

src/main/asciidoc/query-languages/sql/sql-alter-type.adoc
* Add `ALIASES` attribute to `ALTER TYPE` SQL command with example (Section 8.2)
* Remove unused `Support` column form attribute table under ALTER TYPE (Section 8.2)
=> Add ALIASES to ALTER TYPE
